# This Makefile builds the parser
# TODO: use src/ include/ build/ bin/ directory structure?
SOURCEDIR=. lexerutils
BUILDDIR=build
BINARY=parser

COMPILEFLAGS=-g

# C files that are built by flex/bison and cannot be found automatically
EXTRASOURCES=lex.yy.c parser.tab.c

# extra files generated by flex/bison (to be removed on make clean)
EXTRAFILES=lex.yy.h parser.tab.h parser.output

# "build everything" inspired by https://stackoverflow.com/a/3774731
SOURCES:=$(shell find $(SOURCEDIR) -maxdepth 1 -name '*.c') $(EXTRASOURCES)
OBJECTS:=$(addprefix $(BUILDDIR)/,$(SOURCES:%.c=%.o))

$(BINARY): $(EXTRAFILES) $(OBJECTS)
	$(CC) -o $(BINARY) $(OBJECTS)

# special targets (flex/bison)
lex.yy.c lex.yy.h: lexer.l parser.tab.h
	flex --header-file=lex.yy.h lexer.l

parser.tab.c parser.tab.h: parser.y
	bison -vd parser.y

# generic targets
$(BUILDDIR)/%.o: %.c
	mkdir -p $(dir $@)
	$(CC) $(COMPILEFLAGS) -c -o $@ $<

.PHONY:
clean:
	rm -rf build $(EXTRASOURCES) $(EXTRAFILES) $(BINARY)
