# This Makefile builds the parser
# TODO: use src/ include/ build/ bin/ directory structure?
SOURCEDIR:=src
BUILDDIR:=target
INCLUDEDIR:=include include/lexerutils $(BUILDDIR)
BINARY:=parser

CCFLAGS=-g $(addprefix -I,$(INCLUDEDIR))

# C files that are built by flex/bison and cannot be found automatically
EXTRASOURCES=$(addprefix $(BUILDDIR)/,lex.yy.c parser.tab.c)

# extra headers generated by flex/bison (to be removed on make clean)
EXTRAHEADERS=$(addprefix $(BUILDDIR)/,lex.yy.h parser.tab.h)

SOURCES:=$(shell find $(SOURCEDIR) -name '*.c')
OBJECTS:=$(addprefix $(BUILDDIR)/,$(SOURCES:$(SOURCEDIR)/%.c=%.o))

SOURCES+=$(EXTRASOURCES)
OBJECTS+=$(EXTRASOURCES:/%.c=%.o)

$(BINARY): $(EXTRAHEADERS) $(OBJECTS)
	$(CC) $(CCFLAGS) -o $(BINARY) $(OBJECTS)

$(EXTRAHEADERS) $(EXRASOURCES): $(SOURCEDIR)/parser.y $(SOURCEDIR)/lexer.l
	mkdir -p $(dir $@)
	bison -o $(BUILDDIR)/parser.tab.c --defines=$(BUILDDIR)/parser.tab.h \
		-v $(SOURCEDIR)/parser.y
	flex -o $(BUILDDIR)/lex.yy.c --header-file=$(BUILDDIR)/lex.yy.h \
		$(SOURCEDIR)/lexer.l

# generic targets
$(BUILDDIR)/%.o: $(SOURCEDIR)/%.c
	mkdir -p $(dir $@)
	$(CC) $(CCFLAGS) -c -o $@ $<

.PHONY:
clean:
	rm -rf $(BUILDDIR) $(EXTRASOURCES) $(EXTRAHEADERS) $(BINARY)
